// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    CollapsedMenu: typeof import('./../src/components/resource/CollapsedMenu.vue')['default']
    ConfigPanel: typeof import('./../src/components/config-panel/ConfigPanel.vue')['default']
    EditorLayout: typeof import('./../src/layouts/EditorLayout.vue')['default']
    LocalFile: typeof import('./../src/components/resource/LocalFile.vue')['default']
    LpResourceBox: typeof import('@chiulipine/components')['LpResourceBox']
    LpSplitPanes: typeof import('@chiulipine/components')['LpSplitPanes']
    PreviewCanvas: typeof import('./../src/components/preview/PreviewCanvas.vue')['default']
    PreviewFooter: typeof import('./../src/components/preview/PreviewFooter.vue')['default']
    PreviewSection: typeof import('./../src/components/preview/PreviewSection.vue')['default']
    Resource: typeof import('./../src/components/resource/Resource.vue')['default']
    ResourceBox: typeof import('./../src/components/resource/ResourceBox.vue')['default']
    ResourceFragment: typeof import('./../src/components/resource/ResourceFragment.vue')['default']
    ResourceSection: typeof import('./../src/components/resource/ResourceSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLayout: typeof import('./../src/layouts/SectionLayout.vue')['default']
    Splitter: typeof import('./../src/components/Splitter.vue')['default']
    TimeLine: typeof import('./../src/components/tracks/TimeLine.vue')['default']
    TrackBorder: typeof import('./../src/components/tracks/TrackBorder.vue')['default']
    TrackBox: typeof import('./../src/components/TrackBox.vue')['default']
    TrackContainer: typeof import('./../src/components/tracks/TrackContainer.vue')['default']
    TrackHead: typeof import('./../src/components/tracks/TrackHead.vue')['default']
    Tracks: typeof import('./../src/components/tracks/Tracks.vue')['default']
  }
}

export {}
