import { defineConfig } from 'vitepress';

import { sidebar, nav } from './data';

export default defineConfig({
  lang: 'en-US',
  title: 'ChiuLiPine',
  description: 'Vite & Vue powered static site generator.',

  lastUpdated: true,

  themeConfig: {
    editLink: {
      pattern: 'https://github.com/asd55667/chiulipine/edit/dev/packages/:path',
      text: 'Edit this page on GitHub',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/asd55667/chiulipine' }],

    footer: {
      message: 'Generated By VitePress',
      copyright: 'Copyright © 2019-present Evan You',
    },

    algolia: {
      appId: '8J64VVRP8K',
      apiKey: 'a18e2f4cc5665f6602c5631fd868adfd',
      indexName: 'vitepress',
    },

    // carbonAds: {
    //   code: 'CEBDT27Y',
    //   placement: 'vuejsorg',
    // },

    sidebar,
    nav,
  },
});
