// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    CollapsedMenu: typeof import('./../src/components/resource/CollapsedMenu.vue')['default']
    ConfigPanel: typeof import('./../src/components/config-panel/ConfigPanel.vue')['default']
    EditorLayout: typeof import('./../src/layouts/EditorLayout.vue')['default']
    LocalFile: typeof import('./../src/components/resource/LocalFile.vue')['default']
    LpResourceBox: typeof import('@chiulipine/components')['LpResourceBox']
    Preview: typeof import('./../src/components/preview/Preview.vue')['default']
    Resource: typeof import('./../src/components/resource/Resource.vue')['default']
    ResourceBBox: typeof import('./../src/components/resource/ResourceBBox.vue')['default']
    ResourceBox: typeof import('./../src/components/resource/ResourceBox.vue')['default']
    ResourceFragment: typeof import('./../src/components/resource/ResourceFragment.vue')['default']
    ResourceSection: typeof import('./../src/components/resource/ResourceSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLayout: typeof import('./../src/layouts/SectionLayout.vue')['default']
    Splitter: typeof import('./../src/components/Splitter.vue')['default']
    TimeLine: typeof import('./../src/components/tracks/TimeLine.vue')['default']
    Track: typeof import('./../src/components/Track.vue')['default']
    TrackBorder: typeof import('./../src/components/tracks/TrackBorder.vue')['default']
    TrackContainer: typeof import('./../src/components/tracks/TrackContainer.vue')['default']
    TrackHead: typeof import('./../src/components/tracks/TrackHead.vue')['default']
    Tracks: typeof import('./../src/components/tracks/Tracks.vue')['default']
  }
}

export {}
