// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    CollapsedMenu: typeof import('./components/resource/CollapsedMenu.vue')['default']
    ConfigPanel: typeof import('./components/config-panel/ConfigPanel.vue')['default']
    EditorLayout: typeof import('./layouts/EditorLayout.vue')['default']
    LocalResource: typeof import('./components/resource/LocalResource.vue')['default']
    Preview: typeof import('./components/preview/Preview.vue')['default']
    Resource: typeof import('./components/resource/Resource.vue')['default']
    ResourceBox: typeof import('./components/resource/ResourceBox.vue')['default']
    ResourceList: typeof import('./components/resource/ResourceList.vue')['default']
    ResourceSection: typeof import('./components/resource/ResourceSection.vue')['default']
    ResourceSectionHead: typeof import('./components/resource/ResourceSectionHead.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLayout: typeof import('./layouts/SectionLayout.vue')['default']
    Splitter: typeof import('./components/Splitter.vue')['default']
    TimeLine: typeof import('./components/tracks/TimeLine.vue')['default']
    Track: typeof import('./components/Track.vue')['default']
    TrackBorder: typeof import('./components/tracks/TrackBorder.vue')['default']
    TrackContainer: typeof import('./components/tracks/TrackContainer.vue')['default']
    TrackHead: typeof import('./components/tracks/TrackHead.vue')['default']
    Tracks: typeof import('./components/tracks/Tracks.vue')['default']
  }
}

export {}
